### ISSUE TITLE
Where is the script?

### ISSUE THREAD

**Issue by HughP** [CoEDL/elan-helpers#1]
@benfoley 

Where exactly is the script in this repo?

**Comment by benfoley** [comment]
Oh, this repo was added as a placeholder along with `clan-helpers` and `audio-helpers` repos. 

Turns out we wrote the Elan transcription getter directly into Elpis. It could be useful as a standalone script, so I've copied it out and included it here as a standalone script as `elan-to-json`. It reads an Elan file (or files in a folder) and copies annotations from tiers that you specify by name, tier order or tier type. The data is written to a JSON file along with annotation start and stop times. Hope it's useful!
